# Generated by Django 3.2.3 on 2021-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationmodel_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
