# Generated by Django 3.2.3 on 2021-08-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210720_1331'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='produit',
        ),
        migrations.AddField(
            model_name='ventemodel',
            name='produit',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.ProductModel'),
        ),
    ]
