# Generated by Django 3.2.3 on 2021-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_productmodel_exact_dimension'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='produit',
        ),
        migrations.AddField(
            model_name='ventemodel',
            name='produit',
            field=models.ManyToManyField(to='dashboard.ProductModel'),
        ),
    ]
