# Generated by Django 3.2.3 on 2021-08-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_productmodel_exact_dimension'),
        ('ventes', '0002_auto_20210805_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='produit',
        ),
        migrations.AddField(
            model_name='ventemodel',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel'),
        ),
    ]
