# Generated by Django 3.2.3 on 2021-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_auto_20210805_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='payment_mode',
            field=models.CharField(choices=[(1, 'Espèce'), (2, 'Chèque'), (3, 'Orange Money')], default=1, max_length=100),
        ),
    ]
