# Generated by Django 3.2.3 on 2021-10-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_ventemodel_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='payment_mode',
        ),
    ]
