# Generated by Django 3.2.3 on 2021-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_remove_ventemodel_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='type_de_reglement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ventemodel',
            name='type_de_service',
            field=models.IntegerField(choices=[(0, 'Non défini'), (1, 'Service après vente'), (2, 'Livraison à domicile')], default=0),
        ),
    ]
