# Generated by Django 3.2.3 on 2021-10-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_auto_20211009_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventemodel',
            name='type_de_reglement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ventemodel',
            name='type_de_service',
            field=models.IntegerField(blank=True, choices=[(0, 'Non défini'), (1, 'Service après vente'), (2, 'Livraison à domicile')], default=0, null=True),
        ),
    ]
