# Generated by Django 3.2.3 on 2021-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_auto_20211009_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Prix De Vente'),
        ),
    ]
