# Generated by Django 3.2.3 on 2021-10-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_alter_ventemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix De Vente'),
        ),
    ]
