# Generated by Django 3.2.3 on 2021-10-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0009_alter_ventemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
