# Generated by Django 3.2.3 on 2021-10-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_ventemodel_invoiced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='invoiced',
        ),
    ]
