# Generated by Django 3.2.3 on 2021-10-23 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientmodel_updated_date'),
        ('ventes', '0011_remove_ventemodel_invoiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_r_name', related_query_name='client_r_query', to='clients.clientmodel'),
        ),
    ]
