# Generated by Django 3.2.3 on 2021-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_alter_ventemodel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='price_remise',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Prix remise'),
        ),
    ]
