# Generated by Django 3.2.3 on 2021-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
