# Generated by Django 3.2.3 on 2021-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210720_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='garantie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='matière',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('TELEPHONE', 'Telephone'), ('TABLETTE', 'Tablette'), ('ORDINATEUR', 'Ordinateur'), ('TELEVISION', 'Television'), ('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('CONNECTIQUE', 'Connectique'), ('LED', 'Led'), ('BIJOUX', 'Bijoux'), ('ENFANTS_ET_BÉBÉS', 'Enfants_et_bébés'), ('MONTRE', 'Montre'), ('ÉLECTROMÉNAGÉ', 'Électroménagé'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
    ]
