# Generated by Django 3.2.3 on 2021-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210728_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='matière',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
