# Generated by Django 3.2.3 on 2021-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_productmodel_matière'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='matière',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
