# Generated by Django 3.2.3 on 2021-08-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210728_2243'),
        ('dashboard', '0006_productmodel_exact_dimension'),
    ]

    operations = [
    ]
