<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-08-06 21:49
=======
# Generated by Django 3.2.3 on 2021-08-05 15:33
>>>>>>> 2c6f0867399905181c814c7fc737765c52cc4d0b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20210802_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='exact_dimension',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
