# Generated by Django 3.2.3 on 2021-10-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogo',
            name='logo',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
    ]
