# Generated by Django 3.2.3 on 2021-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_companylogo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('TELEPHONE', 'Telephone'), ('TABLETTE', 'Tablette'), ('ORDINATEUR', 'Ordinateur'), ('TELEVISION', 'Television'), ('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('CONNECTIQUE', 'Connectique'), ('LED', 'Led'), ('BIJOUX', 'Bijoux'), ('ENFANTS_ET_BÉBÉS', 'Enfants_et_bébés'), ('MONTRE', 'Montre'), ('ÉLECTROMÉNAGÉ', 'Électroménagé'), ('MONTRE', 'Montre'), ('LIVRE', 'Livre'), ('FRIPERIE', 'Friperie'), ('JEUXVIDEO', 'Jeux Video'), ('LUXE', 'Luxe'), ('CUISINE', 'Cuisine'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
    ]
