# Generated by Django 3.2.3 on 2021-07-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('new_price', models.IntegerField(null=True, verbose_name='Prix neuf')),
                ('used_price', models.IntegerField(blank=True, null=True, verbose_name='Prix occasion')),
                ('estate', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('POUR_PIECE', 'Pour Piece')], max_length=20, null=True)),
                ('obsolescence', models.CharField(choices=[('TRES_RAPIDE', 'Tres_Rapide'), ('RAPIDE', 'Rapide'), ('MOYENNE', 'Moyenne'), ('LENTE', 'Lente')], max_length=20, null=True)),
                ('rarety', models.CharField(choices=[('RARE', 'Rare'), ('COURANT', 'Courant'), ('TRES_COURANT', 'Tres courant')], max_length=20, null=True)),
                ('sale_bill', models.BooleanField(default=False)),
                ('dimension', models.CharField(choices=[('PETIT', 'Petit'), ('MOYEN', 'Moyen'), ('GRAND', 'Grand')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('charger', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('PAS_BESOIN', 'Pas_besoin')], max_length=20, null=True)),
                ('original_box', models.BooleanField(default=False)),
                ('year_of_release', models.IntegerField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reparatinon_price', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, choices=[('TELEPHONE', 'Telephone'), ('TABLETTE', 'Tablette'), ('ORDINATEUR', 'Ordinateur'), ('TELEVISION', 'Television'), ('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('AUTRES', 'Autre')], max_length=100, null=True)),
                ('final_price', models.IntegerField(blank=True, default=0, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.clientmodel')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop')),
            ],
        ),
    ]
