# Generated by Django 3.2.3 on 2021-06-16 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Telephone')),
                ('agency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agence')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Femelle')], null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
