# Generated by Django 3.2.3 on 2021-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210710_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
