# Generated by Django 3.2.3 on 2021-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210711_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], default=1, null=True),
        ),
    ]
