# Generated by Django 3.2.3 on 2021-10-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devismodel',
            name='price_remise',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
