# Generated by Django 3.2.3 on 2021-10-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devismodel_price_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devismodel',
            name='description',
        ),
    ]
