# Generated by Django 3.2.3 on 2021-06-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_du_client', models.CharField(max_length=100)),
                ('nom_du_client', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('address_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_produit', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('annee', models.DateField()),
                ('nombre_de_giga', models.IntegerField()),
                ('nombre_de_ram', models.IntegerField()),
                ('dimensions', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Dimensions')),
                ('poids', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Masse')),
                ('chargeurs', models.BooleanField(default=True)),
                ('boite_origine', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('qualite', models.CharField(choices=[('EXCELLENT', 'Excellente'), ('NORMAL', 'Normale'), ('MAUVAISE', 'Mauvaise')], max_length=20)),
                ('date_d_achat', models.DateTimeField(auto_now_add=True)),
                ('prix_d_achat', models.DecimalField(decimal_places=3, max_digits=20, verbose_name="Prix d'achat")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demander', models.DateTimeField(auto_now_add=True)),
                ('produit_demander', models.CharField(max_length=100)),
                ('produit_trouver', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_vente', models.DateTimeField(auto_now_add=True)),
                ('prix_de_vente_min', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix de vente minimum')),
                ('prix_de_vente_fin', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix de vente final')),
                ('garantie', models.BooleanField(default=False)),
                ('delai_garantie', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel')),
            ],
        ),
    ]
