# Generated by Django 3.2.3 on 2021-06-12 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_vente', models.DateTimeField(auto_now_add=True)),
                ('prix_de_vente_min', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix de vente minimum')),
                ('prix_de_vente_fin', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix de vente final')),
                ('garantie', models.BooleanField(default=False)),
                ('delai_garantie', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_du_client', models.CharField(max_length=100)),
                ('nom_du_client', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('address_email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demander', models.DateTimeField(auto_now_add=True)),
                ('produit_demander', models.CharField(max_length=100)),
                ('produit_trouver', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DepositStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('qualite', models.CharField(choices=[('EXCELLENT', 'Excellente'), ('NORMAL', 'Normale'), ('MAUVAISE', 'Mauvaise')], max_length=20)),
                ('date_d_achat', models.DateTimeField(auto_now_add=True)),
                ('prix_d_achat', models.DecimalField(decimal_places=3, max_digits=20, verbose_name="Prix d'achat")),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_produit', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('annee', models.DateField()),
                ('nombre_de_giga', models.IntegerField()),
                ('nombre_de_ram', models.IntegerField()),
                ('dimensions', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Dimensions')),
                ('poids', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Masse')),
                ('chargeurs', models.BooleanField(default=True)),
                ('boite_origine', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_boutique', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.buyingstockmodel')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientmodel')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.depositstockmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel')),
                ('requete_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientrequestmodel')),
            ],
        ),
        migrations.AddField(
            model_name='depositstockmodel',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel'),
        ),
        migrations.AddField(
            model_name='buyingstockmodel',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel'),
        ),
    ]
