# Generated by Django 3.2.3 on 2021-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='annee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='dimensions',
            field=models.CharField(max_length=20, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='nombre_de_giga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='nombre_de_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
