# Generated by Django 3.2.3 on 2021-06-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotventemodel',
            old_name='min_price',
            new_name='price',
        ),
    ]
