# Generated by Django 3.2.3 on 2021-07-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimationModel',
        ),
    ]
