# Generated by Django 3.2.3 on 2021-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='passage',
            field=models.IntegerField(default=1),
        ),
    ]
