# Generated by Django 3.2.3 on 2021-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='vente_or_achat',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='vente_or_achat',
            field=models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente')], default='ACHAT', max_length=100),
        ),
        migrations.AlterField(
            model_name='ventemodel',
            name='acompte',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name="L'avance du client"),
        ),
        migrations.AlterUniqueTogether(
            name='clientmodel',
            unique_together={('fname', 'lname', 'numero')},
        ),
    ]
