# Generated by Django 3.2.3 on 2021-06-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demander', models.DateTimeField(auto_now_add=True)),
                ('produit_demander', models.CharField(max_length=100)),
                ('produit_trouver', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='demande_client',
        ),
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='date_de_vente',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='garantie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='address_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='depositstockmodel',
            name='prix_d_achat',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='chargeurs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='dimensions',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Masse'),
        ),
        migrations.AddField(
            model_name='clientrequestmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clientmodel'),
        ),
    ]
