# Generated by Django 3.2.3 on 2021-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_productmodel_price_total_tt_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix De Vente'),
        ),
    ]
