# Generated by Django 3.2.3 on 2021-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_shop_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='nom_du_produit',
            new_name='name',
        ),
    ]
