# Generated by Django 3.2.3 on 2021-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210612_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='delai_garantie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='prix_de_vente_fin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Prix de vente final'),
        ),
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='prix_de_vente_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Prix de vente minimum'),
        ),
    ]
