# Generated by Django 3.2.3 on 2021-06-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210624_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='passage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
