# Generated by Django 3.2.3 on 2021-06-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clientmodel_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop'),
        ),
    ]
