# Generated by Django 3.2.3 on 2021-06-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_productmodel_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatdirectmodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.clientmodel'),
        ),
    ]
