# Generated by Django 3.2.3 on 2021-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210612_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='prix_de_vente_fin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix de vente final'),
        ),
        migrations.AlterField(
            model_name='buyingstockmodel',
            name='prix_de_vente_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix de vente minimum'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Masse'),
        ),
    ]
