# Generated by Django 3.2.3 on 2021-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_ventemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('TELEPHONE', 'Telephone'), ('TABLETTE', 'Tablette'), ('ORDINATEUR', 'Ordinateur'), ('TELEVISION', 'Television'), ('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('TELEPHONE', 'Telephone'), ('TABLETTE', 'Tablette'), ('ORDINATEUR', 'Ordinateur'), ('TELEVISION', 'Television'), ('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
    ]
