# Generated by Django 3.2.3 on 2021-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_clientmodel_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='montant_restauration',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Montant de la Restauration'),
        ),
    ]
