# Generated by Django 3.2.3 on 2021-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_achatdirectmodel_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='sale_price_on_new',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name="Prix d'Achat"),
        ),
    ]
