# Generated by Django 3.2.3 on 2021-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210612_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='annee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
