# Generated by Django 3.2.3 on 2021-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210618_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='acompte',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name="l'avance du client"),
        ),
    ]
