# Generated by Django 3.2.3 on 2021-06-14 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_productmodel_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotVenteStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('qualite', models.CharField(choices=[('EXCELLENT', 'Excellente'), ('NORMAL', 'Normale'), ('MAUVAISE', 'Mauvaise')], max_length=20)),
                ('date_d_achat', models.DateTimeField(auto_now_add=True)),
                ('prix_d_achat', models.DecimalField(decimal_places=3, max_digits=20, verbose_name="Prix d'achat")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmodel')),
            ],
        ),
    ]
