# Generated by Django 3.2.3 on 2021-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_productmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='charger',
            field=models.BooleanField(default=False),
        ),
    ]
