# Generated by Django 3.2.3 on 2021-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ventemodel_acompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
    ]
