# Generated by Django 3.2.3 on 2021-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210627_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix De Vente Final'),
        ),
    ]
