# Generated by Django 3.2.3 on 2021-06-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_depotventestockmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotventestockmodel',
            old_name='date_d_achat',
            new_name='date_d_depot',
        ),
        migrations.RenameField(
            model_name='depotventestockmodel',
            old_name='prix_d_achat',
            new_name='prix_d_depot',
        ),
    ]
