# Generated by Django 3.2.3 on 2021-06-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_ventemodel_price_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='quantity',
        ),
    ]
