# Generated by Django 3.2.3 on 2021-06-15 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210615_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositstockmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
