# Generated by Django 3.2.3 on 2021-06-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_depotventemodel_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotventemodel',
            name='client',
        ),
    ]
