# Generated by Django 3.2.3 on 2021-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ventemodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name="Prix D'Achat Total"),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
