# Generated by Django 3.2.3 on 2021-06-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210628_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='prix proposed')),
                ('price_total', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='prix proposed')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.clientmodel')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop')),
            ],
        ),
    ]
