# Generated by Django 3.2.3 on 2021-06-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_devismodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='devismodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devismodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
