# Generated by Django 3.2.3 on 2021-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210630_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationmodel',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estimationmodel',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='charger',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('PAS_BESOIN', 'Pas_besoin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='dimension',
            field=models.CharField(choices=[('PETIT', 'Petit'), ('MOYEN', 'Moyen'), ('GRAND', 'Grand')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='estate',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('POUR_PIECE', 'Pour Piece')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='new_price',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='Prix neuf'),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='obsolescence',
            field=models.CharField(choices=[('TRES_RAPIDE', 'Tres_Rapide'), ('RAPIDE', 'Rapide'), ('MOYENNE', 'Moyenne'), ('LENTE', 'Lente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='rarety',
            field=models.CharField(choices=[('RARE', 'Rare'), ('COURANT', 'Courant'), ('TRES_COURANT', 'Tres courant')], max_length=20, null=True),
        ),
    ]
