# Generated by Django 3.2.3 on 2021-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210701_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='vente_or_achat',
            field=models.CharField(choices=[('CR', 'Client Regulier'), ('CV', 'Vendeur')], default='CR', max_length=100),
        ),
    ]
