# Generated by Django 3.2.3 on 2021-07-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_clientmodel_vente_or_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.shop'),
        ),
    ]
