# Generated by Django 3.2.3 on 2021-07-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210702_1150'),
        ('dashboard', '0017_alter_productmodel_shop'),
    ]

    operations = [
    ]
