# Generated by Django 3.2.3 on 2021-07-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_merge_20210702_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='initial_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
