# Generated by Django 3.2.3 on 2021-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210704_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationmodel',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='initial_quantity',
            field=models.IntegerField(blank=True, default=1, editable=False, null=True),
        ),
    ]
