# Generated by Django 3.2.3 on 2021-07-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210704_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationmodel',
            name='delete',
        ),
    ]
