# Generated by Django 3.2.3 on 2021-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_estimationmodel_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationmodel',
            name='client_name',
        ),
        migrations.AddField(
            model_name='estimationmodel',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.clientmodel'),
        ),
    ]
