# Generated by Django 3.2.3 on 2021-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210706_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('ELECTRONIQUE', 'Electronique'), ('VETEMENT', 'Vetement'), ('DECORATIONS', 'Decorations'), ('ENFANT', 'Telephoniques'), ('AMMEUBLEMENT', 'Ammeublement'), ('LOISIRS', 'Loisirs'), ('IMAGES_ET_SONS', 'Images_et_sons'), ('AUTRES', 'Autre')], max_length=100, null=True),
        ),
    ]
