# Generated by Django 3.2.3 on 2021-07-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_estimationmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationmodel',
            name='reparatinon_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
