# Generated by Django 3.2.3 on 2021-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_estimationmodel_reparatinon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price_vente_minimum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix Vente Minimu'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='montant_restauration',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Montant de la Restauration'),
        ),
    ]
