# Generated by Django 3.2.3 on 2021-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210706_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='price_vente_minimum',
            new_name='price_vente_minimum_ad',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price_vente_minimum_dv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Prix Vente Minimu'),
        ),
    ]
