# Generated by Django 3.2.3 on 2021-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20210706_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationmodel',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='new_price',
            field=models.IntegerField(null=True, verbose_name='Prix neuf'),
        ),
        migrations.AlterField(
            model_name='estimationmodel',
            name='used_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prix occasion'),
        ),
    ]
