# Generated by Django 3.2.3 on 2021-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210708_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationmodel',
            name='final_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
