# Generated by Django 3.2.3 on 2021-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_estimationmodel_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventemodel',
            name='restant_du',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Restant du Client'),
        ),
        migrations.AlterField(
            model_name='ventemodel',
            name='acompte',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name="L'avance du client"),
        ),
    ]
