# Generated by Django 3.2.3 on 2021-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210708_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='connectic',
            field=models.BooleanField(default=False),
        ),
    ]
