# Generated by Django 3.2.3 on 2021-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_productmodel_connectic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequestmodel',
            name='wished_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
